PROJECT		= dip
VCDFORMAT	= vcd

GHDLSTD			= 08
GHDLOPTIONS		= -v -g -P../ttl
GHDLSIMOPTIONS	= --backtrace-severity=warning
#GHDLSIMOPTIONS	+= --assert-level=warning

SRCS = dip.vhd \
	   dip_16dummy.vhd \
	   dip_2147.vhd \
	   dip_25ls2519.vhd \
	   dip_25s07.vhd \
	   dip_25s09.vhd \
	   dip_25s10.vhd \
	   dip_5600.vhd \
	   dip_5610.vhd \
	   dip_7428.vhd \
	   dip_74ls109.vhd \
	   dip_74ls14.vhd \
	   dip_74ls244.vhd \
	   dip_74s00.vhd

include ../ghdl.mk
