library ieee;
use ieee.std_logic_1164.all;

entity cadr_contrl is
  port (
    \-destspc\      : in     std_logic;
    \-destspcd\     : in     std_logic;
    \-funct2\       : in     std_logic;
    \-irdisp\       : in     std_logic;
    \-jcond\        : in     std_logic;
    \-nop11\        : in     std_logic;
    \-reset\        : in     std_logic;
    \-srcspc\       : in     std_logic;
    \-srcspcpop\    : in     std_logic;
    \-trap\         : in     std_logic;
    clk3c           : in     std_logic;
    dn              : in     std_logic;
    dp              : in     std_logic;
    dr              : in     std_logic;
    hi4             : in     std_logic;
    ir42            : in     std_logic;
    ir6             : in     std_logic;
    ir7             : in     std_logic;
    ir8             : in     std_logic;
    ir9             : in     std_logic;
    irdisp          : in     std_logic;
    irjump          : in     std_logic;
    jcond           : in     std_logic;
    tse3a           : in     std_logic;
    wp4c            : in     std_logic;
    \-dfall\        : inout  std_logic;
    \-dp\           : inout  std_logic;
    \-dr\           : inout  std_logic;
    \-ignpopj\      : inout  std_logic;
    \-inop\         : inout  std_logic;
    \-ipopj\        : inout  std_logic;
    \-ir6\          : inout  std_logic;
    \-ir8\          : inout  std_logic;
    \-iwrited\      : inout  std_logic;
    \-nop\          : inout  std_logic;
    \-nopa\         : inout  std_logic;
    \-popj\         : inout  std_logic;
    \-spop\         : inout  std_logic;
    \-spush\        : inout  std_logic;
    \-spushd\       : inout  std_logic;
    \-srcspcpopreal\ : inout  std_logic;
    destspc         : inout  std_logic;
    dispenb         : inout  std_logic;
    iwrite          : inout  std_logic;
    iwrited         : inout  std_logic;
    jcalf           : inout  std_logic;
    jfalse          : inout  std_logic;
    jret            : inout  std_logic;
    jretf           : inout  std_logic;
    n               : inout  std_logic;
    nop             : inout  std_logic;
    popj            : inout  std_logic;
    spcenb          : inout  std_logic;
    spush           : inout  std_logic;
    spushd          : inout  std_logic;
    \-spcdrive\     : out    std_logic;
    \-spcnt\        : out    std_logic;
    \-spcpass\      : out    std_logic;
    \-spcwpass\     : out    std_logic;
    \-swpa\         : out    std_logic;
    \-swpb\         : out    std_logic;
    destspcd        : out    std_logic;
    inop            : out    std_logic;
    pcs0            : out    std_logic;
    pcs1            : out    std_logic;
    spcdrive        : out    std_logic;
    spcwpass        : out    std_logic
  );
end entity;
