library ieee;
use ieee.std_logic_1164.all;

entity cadr_l is
  port (
    clk3f           : in     std_logic;
    ob0             : in     std_logic;
    ob1             : in     std_logic;
    ob10            : in     std_logic;
    ob11            : in     std_logic;
    ob12            : in     std_logic;
    ob13            : in     std_logic;
    ob14            : in     std_logic;
    ob15            : in     std_logic;
    ob16            : in     std_logic;
    ob17            : in     std_logic;
    ob18            : in     std_logic;
    ob19            : in     std_logic;
    ob2             : in     std_logic;
    ob20            : in     std_logic;
    ob21            : in     std_logic;
    ob22            : in     std_logic;
    ob23            : in     std_logic;
    ob24            : in     std_logic;
    ob25            : in     std_logic;
    ob26            : in     std_logic;
    ob27            : in     std_logic;
    ob28            : in     std_logic;
    ob29            : in     std_logic;
    ob3             : in     std_logic;
    ob30            : in     std_logic;
    ob31            : in     std_logic;
    ob4             : in     std_logic;
    ob5             : in     std_logic;
    ob6             : in     std_logic;
    ob7             : in     std_logic;
    ob8             : in     std_logic;
    ob9             : in     std_logic;
    \-lparm\        : inout  std_logic;
    l0              : inout  std_logic;
    l1              : inout  std_logic;
    l10             : inout  std_logic;
    l11             : inout  std_logic;
    l12             : inout  std_logic;
    l13             : inout  std_logic;
    l14             : inout  std_logic;
    l15             : inout  std_logic;
    l16             : inout  std_logic;
    l17             : inout  std_logic;
    l18             : inout  std_logic;
    l19             : inout  std_logic;
    l2              : inout  std_logic;
    l20             : inout  std_logic;
    l21             : inout  std_logic;
    l22             : inout  std_logic;
    l23             : inout  std_logic;
    l24             : inout  std_logic;
    l25             : inout  std_logic;
    l26             : inout  std_logic;
    l27             : inout  std_logic;
    l28             : inout  std_logic;
    l29             : inout  std_logic;
    l3              : inout  std_logic;
    l30             : inout  std_logic;
    l31             : inout  std_logic;
    l4              : inout  std_logic;
    l5              : inout  std_logic;
    l6              : inout  std_logic;
    l7              : inout  std_logic;
    l8              : inout  std_logic;
    l9              : inout  std_logic;
    lparl           : inout  std_logic;
    \-lparity\      : out    std_logic;
    lparity         : out    std_logic
  );
end entity;
