library ieee;
use ieee.std_logic_1164.all;

entity icmem_clock1 is
  port (
    \-clock reset b\ : in     std_logic;
    \-hang\         : in     std_logic;
    \-ilong\        : in     std_logic;
    sspeed0         : in     std_logic;
    sspeed1         : in     std_logic;
    \-tpdone\       : inout  std_logic;
    \-tpr0\         : inout  std_logic;
    \-tpr100\       : inout  std_logic;
    \-tpr115\       : inout  std_logic;
    \-tpr125\       : inout  std_logic;
    \-tpr140\       : inout  std_logic;
    \-tpr160\       : inout  std_logic;
    \-tpr40\        : inout  std_logic;
    \-tpr60\        : inout  std_logic;
    \-tpr75\        : inout  std_logic;
    \-tpr85\        : inout  std_logic;
    \-tprend\       : inout  std_logic;
    \-tpw20\        : inout  std_logic;
    \-tpw50\        : inout  std_logic;
    \-tpw60\        : inout  std_logic;
    cyclecompleted  : inout  std_logic;
    \-tpr105\       : out    std_logic;
    \-tpr10\        : out    std_logic;
    \-tpr110\       : out    std_logic;
    \-tpr120\       : out    std_logic;
    \-tpr120a\      : out    std_logic;
    \-tpr15\        : out    std_logic;
    \-tpr180\       : out    std_logic;
    \-tpr200\       : out    std_logic;
    \-tpr20\        : out    std_logic;
    \-tpr20a\       : out    std_logic;
    \-tpr25\        : out    std_logic;
    \-tpr5\         : out    std_logic;
    \-tpr65\        : out    std_logic;
    \-tpr70\        : out    std_logic;
    \-tpr80\        : out    std_logic;
    \-tpr80a\       : out    std_logic;
    \-tpw10\        : out    std_logic;
    \-tpw25\        : out    std_logic;
    \-tpw30\        : out    std_logic;
    \-tpw30a\       : out    std_logic;
    \-tpw35\        : out    std_logic;
    \-tpw40\        : out    std_logic;
    \-tpw40a\       : out    std_logic;
    \-tpw45\        : out    std_logic;
    \-tpw55\        : out    std_logic;
    \-tpw65\        : out    std_logic;
    \-tpw70\        : out    std_logic;
    \-tpw75\        : out    std_logic;
    tprend          : out    std_logic
  );
end entity;
