library ieee;
use ieee.std_logic_1164.all;

entity icmem_olord1 is
  port (
    \-boot\         : in     std_logic;
    \-clock reset a\ : in     std_logic;
    \-errhalt\      : in     std_logic;
    \-icmem reset\  : in     std_logic;
    \-ldclk\        : in     std_logic;
    \-ldmode\       : in     std_logic;
    \-ldopc\        : in     std_logic;
    \-stc32\        : in     std_logic;
    \-tpr60\        : in     std_logic;
    \-wait\         : in     std_logic;
    mclk5a          : in     std_logic;
    spy0            : in     std_logic;
    spy1            : in     std_logic;
    spy2            : in     std_logic;
    spy3            : in     std_logic;
    spy4            : in     std_logic;
    spy5            : in     std_logic;
    statstop        : in     std_logic;
    \-ssdone\       : inout  std_logic;
    \-stathalt\     : inout  std_logic;
    machrun         : inout  std_logic;
    promdisable     : inout  std_logic;
    run             : inout  std_logic;
    speed0          : inout  std_logic;
    speed0a         : inout  std_logic;
    speed1          : inout  std_logic;
    speed1a         : inout  std_logic;
    speedclk        : inout  std_logic;
    srun            : inout  std_logic;
    ssdone          : inout  std_logic;
    sstep           : inout  std_logic;
    stathenb        : inout  std_logic;
    step            : inout  std_logic;
    \-idebug\       : out    std_logic;
    \-ldstat\       : out    std_logic;
    \-lpc.hold\     : out    std_logic;
    \-machrun\      : out    std_logic;
    \-machruna\     : out    std_logic;
    \-nop11\        : out    std_logic;
    \-opcclk\       : out    std_logic;
    \-opcinh\       : out    std_logic;
    \-run\          : out    std_logic;
    \-step\         : out    std_logic;
    \lpc.hold\      : out    std_logic;
    \stat.ovf\      : out    std_logic;
    errstop         : out    std_logic;
    idebug          : out    std_logic;
    ldstat          : out    std_logic;
    nop11           : out    std_logic;
    opcclk          : out    std_logic;
    opcinh          : out    std_logic;
    promdisabled    : out    std_logic;
    sspeed0         : out    std_logic;
    sspeed1         : out    std_logic;
    trapenb         : out    std_logic
  );
end entity;
