library ieee;
use ieee.std_logic_1164.all;

entity icmem_olord2 is
  port (
    \-busint.lm.reset\ : in     std_logic;
    \-halt\         : in     std_logic;
    \-ldmode\       : in     std_logic;
    \-upperhighok\  : in     std_logic;
    \prog.bus.reset\ : in     std_logic;
    \stat.ovf\      : in     std_logic;
    aparok          : in     std_logic;
    clk5            : in     std_logic;
    dparok          : in     std_logic;
    errstop         : in     std_logic;
    iparok          : in     std_logic;
    mclk5           : in     std_logic;
    memparok        : in     std_logic;
    mmemparok       : in     std_logic;
    pdlparok        : in     std_logic;
    spcparok        : in     std_logic;
    spy6            : in     std_logic;
    spy7            : in     std_logic;
    srun            : in     std_logic;
    v0parok         : in     std_logic;
    vmoparok        : in     std_logic;
    \-ape\          : inout  std_logic;
    \-boot1\        : inout  std_logic;
    \-boot2\        : inout  std_logic;
    \-boot\         : inout  std_logic;
    \-clk5\         : inout  std_logic;
    \-clock reset a\ : inout  std_logic;
    \-clock reset b\ : inout  std_logic;
    \-dpe\          : inout  std_logic;
    \-halted\       : inout  std_logic;
    \-higherr\      : inout  std_logic;
    \-ipe\          : inout  std_logic;
    \-lowerhighok\  : inout  std_logic;
    \-mclk5\        : inout  std_logic;
    \-mempe\        : inout  std_logic;
    \-mpe\          : inout  std_logic;
    \-pdlpe\        : inout  std_logic;
    \-power reset\  : inout  std_logic;
    \-prog.reset\   : inout  std_logic;
    \-spe\          : inout  std_logic;
    \-v0pe\         : inout  std_logic;
    \-v1pe\         : inout  std_logic;
    \power reset a\ : inout  std_logic;
    \prog.boot\     : inout  std_logic;
    clk5a           : inout  std_logic;
    err             : inout  std_logic;
    hi1             : inout  std_logic;
    hi2             : inout  std_logic;
    highok          : inout  std_logic;
    ldmode          : inout  std_logic;
    mclk5a          : inout  std_logic;
    reset           : inout  std_logic;
    \-bus.power.reset\ : out    std_logic;
    \-bus.reset\    : out    std_logic;
    \-errhalt\      : out    std_logic;
    \-icmem reset\  : out    std_logic;
    \boot.trap\     : out    std_logic;
    statstop        : out    std_logic
  );
end entity;
