name: CADR4 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Fossil
      run: sudo apt-get install -y fossil

    - name: Install GHDL
      run: sudo apt-get install -y ghdl

    - name: Build ttl
      run: make -C ttl all

    - name: Test ttl
      run: make -C ttl test

    - name: Build cadr
      run: make all

    - name: Test cadr
      run: make test
