name: CADR CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: apt update
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install -y software-properties-common build-essential

    - name: Install GHDL
      run: sudo apt-get install -y ghdl-llvm

    - name: Install latest LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Fix libLLVM-18.so.18.1 path (symlink)
      run: sudo ln -s /lib/x86_64-linux-gnu/libLLVM.so.18.1 /lib/x86_64-linux-gnu/libLLVM-18.so.18.1	

    - name: Regen
      run: make regen

    - name: Build with ghdl
      run: make clean && CADR4_HDLCOMPILER=ghdl make

    - name: Install nvc dependencies
      run: sudo apt-get install -y git autoconf flex pkg-config zlib1g-dev libzstd-dev

    - name: Get nvc
      run: git clone https://github.com/nickg/nvc

    - name: Build nvc
      run: |
        cd nvc
        ./autogen.sh
        mkdir build
        cd build
        ../configure --with-llvm=/usr/bin/llvm-config-20
        make
        sudo make install

    - name : Build with nvc
      run: make clean && CADR4_HDLCOMPILER=nvc make