name: CADR4 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Fossil
      run: sudo apt-get install -y fossil

    - name: Install GHDL
      run: sudo apt-get install -y ghdl

    - name: Run test
      run: make test
